Controllers/SessionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MB_Pipeline.Controllers
{
    public class SessionsController : Controller
    {
        //
        // GET: /Sessions/

        public ActionResult Index()
        {

            return View();
        }

        //5
        // POST /Sessions/New
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult New()
        {
            if (Helper.Sessions.LoginUser(Request.Params["email"], Request.Params["password"], Request.Params["remember"]))
            {
                if (Request.Params["ReturnUrl"] != null)
                {
                    return Redirect(Request.Params["ReturnUrl"]);
                }
                else
                {
                    return Redirect("/");
                }
            }
            else
            {
                string[] error = { "User name or password is incorrect." };
                TempData["Error"] = error;
                return RedirectToAction("Index");
            }
        }

        //
        //Post /Sessions/Delete
        public ActionResult Delete()
        {
            Helper.Sessions.LogoutUser();
            return Redirect("/");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>MB Pipeline | @ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        }
    </style>
    <link href="~/Content/bootstrap-responsive.min.css" rel="stylesheet">
    <!-- Le styles -->
    @Styles.Render("~/Content/themes/base/css", "~/Content/css")

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="~/Content/icons/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/Content/icons/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/Content/icons/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/Content/icons/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="~/Content/icons/apple-touch-icon-57-precomposed.png">
</head>

<body>
     <div id="modal_wrap">
         <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="myModalLabel"></h3>
            </div>
            <div class="modal-body">
            </div>
        </div>
     </div>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="brand" href="/">MB Pipeline</a>
                @if (this.User.Identity.IsAuthenticated)
                {
                    <div class="pull-left">
                        <ul class="nav">
                            <li class="@(ViewBag.Title == "Accounts" ? "active" : "")"><a href="/Accounts">Accounts</a></li>
                            <li class="@(ViewBag.Title == "Maps" ? "active" : "")"><a href="/Maps">Maps</a></li>
                        </ul>
                    </div>
                }
                <div class="pull-right">
                    <ul class="nav">
                        <li class="@(ViewBag.Title == "Home" ? "active" : "")"><a href="/">Home</a></li>
                        @if (!this.User.Identity.IsAuthenticated)
                        {
                            <li class="@(ViewBag.Title == "Sign In" ? "active" : "")"><a href="/Signin">Sign In</a></li>
                        }
                        else
                        {
                            <li id="fat-menu" class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Settings", "Edit", "User")</li>
                                    <li class="divider"></li>
                                    <li>@Html.ActionLink("Log out", "Delete", "Sessions")</li>
                                </ul>
                            </li>
                        }
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>
    </div>

    <div class="container">
        @if (TempData["Error"] != null)
        {
            <div class="alert alert-error">
                <ul>
                    @foreach (string error in (string[])TempData["Error"])
                    {
                        <li>@error</li>
                    }
                </ul>
            </div>
        }

        @RenderBody()
        <footer class="footer">
            <small>MB Pipeline
            </small>
            <nav>
                <ul>
                    <li><a href="/about">About</a></li>
                    <li><a href="/contact">Contact</a></li>
                </ul>
            </nav>
        </footer>
    </div>
    <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/site.js"></script>
    @RenderSection("scripts", required: false)
    <script>
        $(function () {
            @if (!string.IsNullOrEmpty(ViewBag.Ready))
            {
                @(ViewBag.Ready + "()".ToString());
            }
        });
    </script>
</body>
</html>

Views/Shared/_Modal.cshtml
<div id="modal_wrap">
    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel">@ViewBag.Title</h3>
        </div>
        <div class="modal-body">
            @RenderBody()
        </div>
    </div>
</div>