Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MB_Pipeline.Controllers
{
    public class LocationsController : Controller
    {
        //
        // GET: /Locations/
        
        [Authorize]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult Index(int location, int account)
        {
            ViewData["Account"] = account;
            var loc = Helper.Locations.GetLocation(location, account);
            List<SelectListItem> states = Helper.Contacts.GetStateDropdown();
            var q = (from SelectListItem item in states
                     where item.Value == loc.state
                     select item).First().Selected = true;
            ViewData["States"] = states;
            return View(loc);
        }

        //GET: /Locations/New
        [Authorize]
        public ActionResult New(int account)
        {
            ViewData["Account"] = account;
            List<SelectListItem> states = Helper.Contacts.GetStateDropdown();
            ViewData["States"] = states;
            return View();
        }

        [Authorize]
        public ActionResult Update()
        {
            var i = new MB_Pipeline.Controllers.Models.Location();
            i.id = Convert.ToInt32(Request["id"]);
            i.name = Request["name"];
            i.address = Request["address"];
            i.address_line2 = Request["address_line2"];
            i.city = Request["city"];
           // i.country = Request["country"];
            i.zip_code = Request["zip_code"];
            i.state = Request["state_dropdown"];
            if (Helper.Locations.Update(i))
            {
                return Redirect("/Accounts/Details/" + Request["Account"]);
            }
            return Redirect("/404");
        }

        [Authorize]
        public ActionResult Save()
        {
            var i = new MB_Pipeline.Controllers.Models.Location();
            i.name = Request["name"];
            i.address = Request["address"];
            i.address_line2 = Request["address_line2"];
            i.city = Request["city"];
           // i.country = Request["country"];
            i.zip_code = Request["zip_code"];
            i.state = Request["state_dropdown"];
            if (Helper.Locations.New(i, Convert.ToInt32(Request["account"])) == true)
            {

                return Redirect("/Accounts/Details/" + Request["Account"]);
            }
            return Redirect("/404");
        }
    }
}

Views/Locations/Index.cshtml
@{
    ViewBag.Title = "Index";
    //Layout = "~/Views/Shared/_Modal.cshtml";
    Layout = null;
}

@using (Html.BeginForm("Update", "Locations", FormMethod.Post))
{
    <input type="hidden" name="id" value="@Model.id" />
    <input type="hidden" name="account" value="@ViewData["Account"]" />
    <p>
        <label for="name">Name:</label>
        <input type="text" name="name" value="@Model.name" />
        <br />
        <label for="address">Address:</label>
        <input type="text" name="address" value="@Model.address" /><br />
        <input type="text" name="address_line2" value="@Model.address_line2" /><br />
        <label for="city">City:</label>
        <input type="text" name="city" value="@Model.city" />
        <label for="state">State:</label>
        @Html.DropDownList("state_dropdown", (List<SelectListItem>)ViewData["States"])
        <br />
        <label for="zip">Postal Code:</label>
        <input type="text" name="zip_code" value="@Model.zip_code" />
        <br />
    </p>

    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <input class="btn btn-large btn-primary" type="submit" name="buttonSubmit" value="Save" />
    </div>

}
<script type="text/javascript">
    $(function () {
        LoadModal('Update Location');
    });
</script>

Views/Locations/New.cshtml
@{
    ViewBag.Title = "Index";
    //Layout = "~/Views/Shared/_Modal.cshtml";
    Layout = null;
}
@using (Html.BeginForm("Save", "Locations", FormMethod.Post))
{
    <input type="hidden" name="account" value="@ViewData["Account"]" />
    <p>
        <label for="name">Name:</label>
        <input type="text" name="name" value="" />
        <br />
        <label for="address">Address:</label>
        <input type="text" name="address" value="" /><br />
        <input type="text" name="address_line2" value="" /><br />
        <label for="city">City:</label>
        <input type="text" name="city" value="" />
        <label for="state">State:</label>
        @Html.DropDownList("state_dropdown", (List<SelectListItem>)ViewData["States"])
        <br />
        <label for="zip">Postal Code:</label>
        <input type="text" name="zip_code" value="" />
        <br />
        <label for="country">Country:</label>
        <input type="text" name="country" value="" />
    </p>

    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <input class="btn btn-large btn-primary" type="submit" name="buttonSubmit" value="Save" />
    </div>

}
<script type="text/javascript">
    $(function () {
        LoadModal('New Location');
    });
</script>